//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTrain.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExercisesTable
    {
        public int id { get; set; }
        public string TrainName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Exercises { get; set; }
        public string PathToVideo { get; set; }
    }
}
