//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTrain.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanTable
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public int Role { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string TrainName { get; set; }
        public string UserResult { get; set; }

        public string FIO
        {
            get
            {
                return $"{LastName} {FirstName}";
            }
        }
        public string DataRole
        {
            get
            {
                if (Role == 1)
                    return "Администратор";
                else if (Role == 2)
                    return "Тренер";
                else
                    return "Спортсмен";
            }
        }
    }
}
