//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportTrain.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingTable
    {
        public string TrainName { get; set; }
        public string TrainDescription { get; set; }
        public byte[] TrainImage { get; set; }
    }
}
